modules_dir = "artifacts/"

[[module]]
    name = "evm_rpc"
    mem_pages_count = 100
    logger_enabled = true

    [module.mounted_binaries]
    curl = "/usr/bin/curl"
    
[[module]]
    name = "meta-contract"
    mem_pages_count = 100
    logger_enabled = true

    [module.mounted_binaries]
    ipfs = "/usr/local/bin/ipfs"
